language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - bundle --version

rvm:
  - 2.3.0
  - 2.3.7
  - 2.4.0
  - 2.4.4
  - 2.5.0
  - 2.5.1
  - 2.5.3
  - 2.6.0
  - jruby-9.1.13.0
  - jruby-9.1.17.0

script:
  - bundle exec rspec
